import { SiteHeader } from '@/components'
import './globals.css'
import { DynaPuff } from 'next/font/google'
const dynapuff = DynaPuff({
    subsets: ['latin'],
    display: 'swap',
  variable: '--font-cursive',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${dynapuff.variable}`}>
      <body>
        <SiteHeader />
        <main>{children}</main>
      </body>
    </html>
  )
}
